[package]
name = "rust-web-app-test"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
opentelemetry = "0.22"
opentelemetry_sdk = "0.22"
opentelemetry-stdout = { version = "0.3", features = ["trace"] }
